name: CD MAIN IO NET8 SIMPLE Build

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

env:
  BUILD_VERSION: '1.0.20'
  DOTNET_VERSION_TARGET: net8.0
  PROJECT_FILE: 'PruebaBlazor8.csproj'
  PROJECT_FOLDER: 'PruebaBlazor8'
  SOLUTION_FOLDER: './PruebaBlazor'
  BUILD_CONFIG: 'Release'
  PACKAGE_NAME: 'com.pruebablazor9'  

permissions:
  contents: write
  issues: read
  packages: write

jobs:

  build-ios:
    runs-on: macos-14

    name: iOS Build and Publish
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the code  (hace el clone del repo)
        uses: actions/checkout@v4     
        with:
          path: ./

      - name: ==Prepara el llavero==
        run: |
          security create-keychain -p "123" "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db"
          security default-keychain -s "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db"
          security unlock-keychain -p "123" "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db"

      - name: Decode b64 el certificado de distribucion desde el secret
        id: import_cert_dist
        run: | 
          echo -n "${{secrets.IOS_CERT_DIST_CONTAIN_BASE64}}" | base64 --decode -o "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/cert_dist.p12"
          
      - name: Importando al llavero - Certificado de distribucion (p12)
        run: |
          security import "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/cert_dist.p12" -P "" -A -t cert -f pkcs12 -k "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "123" "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db"

      - name: Verifica si la clave esta en el llavero
        run: |
          security find-identity -v -p codesigning "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db"

      - name: certificado provisional
        run: |
          mkdir -p "/Users/runner/Library/MobileDevice"
          mkdir -p "/Users/runner/Library/MobileDevice/Provisioning Profiles"
          #
          chmod -R u+rX /Users/runner/Library/MobileDevice
          #
          cp /Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/Certificados/compruebablazor9.mobileprovision \
            "/Users/runner/Library/MobileDevice/Provisioning Profiles/46e806a8-d39e-4479-ba7d-2916be06f4ae.mobileprovision"
          chmod 644 "/Users/runner/Library/MobileDevice/Provisioning Profiles/46e806a8-d39e-4479-ba7d-2916be06f4ae.mobileprovision"
          #~/Library/MobileDevice/Provisioning\ Profiles/com.pruebablazor9.mobileprovision 
           
      - name: test
        run: |
          sudo security cms -D -i "/Users/runner/Library/MobileDevice/Provisioning Profiles/46e806a8-d39e-4479-ba7d-2916be06f4ae.mobileprovision" > /dev/null 

      - name: Setup XCode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
    
      - name: Verify Xcode version
        run: |
          xcodebuild -version

      - name: ruta de desarrollo activo
        run: |
          xcode-select -p
  
      - name: aceptación de licencias y componentes adicionales
        run: |
          xcodebuild -runFirstLaunch

      - name: Setup .NET 8.0.101
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.101

      - name: Elimina la versión NET9 (default)
        run: |
          rm -rf /Users/runner/.dotnet/sdk/9.*
          echo "donet===> $(ls /Users/runner/.dotnet/sdk)"

      - name: Instalar .NET 8
        run: |
          dotnet --info
        env:
          DOTNET_ROOT: /usr/share/dotnet
          DOTNET_VERSION: 8.0.101

      - name: Instalacion MAUI workload
        run: |
          cd /Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/PruebaBlazor/PruebaBlazor8
          dotnet workload restore --skip-manifest-update
          #dotnet workload install ios maui android --version 8.0.101

      - name: Restaurar dependencias
        shell: bash
        run: |      
          dotnet restore "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/PruebaBlazor/PruebaBlazor8/PruebaBlazor8.csproj"

      - name: ==Build Release==
        run: |
          security cms -D -i "/Users/runner/Library/MobileDevice/Provisioning Profiles/46e806a8-d39e-4479-ba7d-2916be06f4ae.mobileprovision"

          dotnet build -v:d "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/PruebaBlazor/PruebaBlazor8/PruebaBlazor8.csproj" \
            -c Release -f net8.0-ios \
            /p:CodesignKey="Apple Distribution: NOTIONS GROUP S.A. (8BU3XBJR6T)" \
            /p:CodesignProvision="com.pruebablazor9" \
            /p:SigningKeychain="/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/build.keychain-db" 

      - name: ==Publish Release==
        run: |
          dotnet publish "/Users/runner/work/maui_blazor_prueba/maui_blazor_prueba/PruebaBlazor/PruebaBlazor8/PruebaBlazor8.csproj" \
            -c Release \
            -f:net8.0-ios /p:ArchiveOnBuild=true --verbosity diagnostic \
             -r ios-arm64 --self-contained --self-contained \
            /p:EnableAssemblyILStripping=false \
            /p:AppStorePackage=true \
            /p:CodesignKey="Apple Distribution: NOTIONS GROUP S.A. (8BU3XBJR6T)" \
            /p:CodesignProvision="46e806a8-d39e-4479-ba7d-2916be06f4ae" \
            /p:ProvisioningProfile="/Users/runner/Library/MobileDevice/Provisioning Profiles/46e806a8-d39e-4479-ba7d-2916be06f4ae.mobileprovision"  \
            /p:AppIdentifier="com.pruebablazor9" \
            /p:BuildIpa=true
                       
